
CREATE SCHEMA IF NOT EXISTS warehouse;

CREATE TABLE IF NOT EXISTS warehouse.dim_date (
date_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
full_date DATE NOT NULL UNIQUE,
day_name VARCHAR (10) NOT NULL,
month_name VARCHAR (10) NOT NULL,
year INT NOT NULL,
day_of_week INT NOT NULL,
week_of_year INT NOT NULL,
month INT NOT NULL,
is_weekend BOOLEAN NOT NULL DEFAULT FALSE
) ;

CREATE TABLE IF NOT EXISTS warehouse.dim_book (
book_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
book_id VARCHAR (36) NOT NULL,
isbn VARCHAR (36),
title VARCHAR (255),
author VARCHAR (255),
effective_from DATE NOT NULL,
effective_to DATE,
is_current BOOLEAN NOT NULL DEFAULT TRUE
) ;


CREATE TABLE IF NOT EXISTS warehouse.dim_course (
course_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
course_id VARCHAR (36) NOT NULL,
course_name VARCHAR (150),
course_code VARCHAR (20)
) ;


CREATE TABLE IF NOT EXISTS warehouse.dim_student (
student_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
student_id VARCHAR (36) NOT NULL,
student_number VARCHAR (20),
course_key INT REFERENCES warehouse.dim_course (course_key),
study_year INT NOT NULL,
effective_from DATE NOT NULL,
effective_to DATE,
is_current BOOLEAN NOT NULL DEFAULT TRUE
) ;

CREATE TABLE IF NOT EXISTS warehouse.fact_loans (
loan_key INT GENERATED BY DEFAULT AS IDENTITY,
loan_id VARCHAR (36) NOT NULL,
date_key INT NOT NULL REFERENCES warehouse.dim_date (date_key),
book_key INT NOT NULL REFERENCES warehouse.dim_book (book_key),
student_key INT NOT NULL REFERENCES warehouse.dim_student (student_key),
course_key INT REFERENCES warehouse.dim_course (course_key),
loan_duration INT,
overdue BOOLEAN NOT NULL DEFAULT FALSE,
fine_amount DOUBLE PRECISION,
status VARCHAR (20),
loan_year INT NOT NULL,

CONSTRAINT fact_loans_id UNIQUE (loan_id, loan_year)
) PARTITION BY RANGE (loan_year) ;


CREATE TABLE warehouse.fact_loans_2026 PARTITION OF warehouse.fact_loans FOR VALUES FROM (2026) TO (2027) ;
CREATE TABLE warehouse.fact_loans_2025 PARTITION OF warehouse.fact_loans FOR VALUES FROM (2025) TO (2026) ;
CREATE TABLE warehouse.fact_loans_2024 PARTITION OF warehouse.fact_loans FOR VALUES FROM (2024) TO (2025) ;
CREATE TABLE warehouse.fact_loans_2023 PARTITION OF warehouse.fact_loans FOR VALUES FROM (2023) TO (2024) ;
CREATE TABLE warehouse.fact_loans_2022 PARTITION OF warehouse.fact_loans FOR VALUES FROM (2022) TO (2023) ;
CREATE TABLE warehouse.fact_loans_2021 PARTITION OF warehouse.fact_loans FOR VALUES FROM (2021) TO (2022) ;


CREATE INDEX idx_fact_loans_date_key ON warehouse.fact_loans (date_key) ;
CREATE INDEX idx_fact_loans_book_key ON warehouse.fact_loans (book_key) ;
CREATE INDEX idx_fact_loans_student_key ON warehouse.fact_loans (student_key) ;
CREATE INDEX idx_fact_loans_course_key ON warehouse.fact_loans (course_key) ;
CREATE INDEX idx_Fact_loans_overdue ON warehouse.fact_loans (overdue) ;

CREATE INDEX idx_dim_date_full_date ON warehouse.dim_date (full_date) ;
CREATE INDEX idx_dim_book_id ON warehouse.dim_book (book_id) ;
